### ISSUE TITLE
Dockerization of the Whole  Application

### ISSUE THREAD

**Issue by GamerSpidey** [BigDataIA-Spring2024-Sec1-Team6/FinalProj_Team6#9]
## Todo
- [ ] Dockerize Frontend Services - Manya
- [ ] Dockerize Backend Services - Osborne
- [ ] Dockerize FastAPI - Osborne
